### ISSUE TITLE
VSCode error

### ISSUE THREAD

**Issue by warriorCoder** [felangel/bloc#1497]
While using version 4.2.2 of the vscode extension I have version 6.x of bloc and flutter bloc but the extension warns that I have an old version of bloc and need to upgrade. 
See attached screenshot.
![image](https://user-images.githubusercontent.com/4119110/88079757-2829c300-cb4c-11ea-8abd-472469b5d28a.png)

**Comment by felangel** [comment]
Hey @warriorCoder 👋 
Thanks for opening an issue!

This is expected until the `v6.0.0` stable is out 👍

**Comment by felangel** [comment]
Addressed in https://github.com/felangel/bloc/commit/9e6224855717d725a70922c34ae5077410d28d6d and published in v5.0.0 of the bloc vscode extension 🎉

**Comment by iChicago** [comment]
I'm using version 5.3.2 of the extension and flutter_bloc: ^6.0.1
However, I still get the same error above.

**Comment by AlirezaGhaznavi** [comment]
You can do this now

- 1  go to setting of Bloc extensions in Vs code
- 2  turn off the 'Check For Updates'
